# SPRING_PROFILES_ACTIVE=tap
# All TAP applications...

# Should register with Spring Boot Admin
spring:  
 boot:
   admin:
     client:
       url: http://spring-boot-admin.default.svc.cluster.local
       instance:
         service-base-url: http://${spring.application.name}.${NAMESPACE}.${DOMAIN}:${PORT}

# Should expose their Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

# Should log to a file (requires logback-spring.xml in their src/main/resources)      
#logging:
#  file:
#    name: "./logs/application.log" 
#  pattern:
#    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# Should shutdown gracefully
server:
  shutdown: graceful # The stop processing uses a timeout which provides a grace period during which existing requests will be allowed to complete but no new requests will be permitted
